baseurl = "http://nishanttotla.com/"
languageCode = "en-us"
title = "nRT"
pygmentsUseClasses = true
theme = "skeleton"
pluralizelisttitles = false
[permalinks]
  notes = "/blog/:filename/"
  monthly-log = "/blog/:filename/"
  weekly-log = "/blog/:filename/"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[params]
  description = "Nishant's Website"
  author = "Nishant Totla"
  authorDescription = "My name is Nishant Totla and I'm a software engineer at Docker. I love the outdoors and adventure. I think about technology, social issues, and the environment."
  siteDescriptors = ["blog", "outdoors", "adventure", "programming", "software", "Nishant Totla", "Nishant", "Totla"]
  authorTwitter = "nishanttotla"
  authorFacebook = "nishanttotla"
  authorGithub = "nishanttotla"
  authorLinkedin = "nishanttotla"
  authorGoogleplus = "nishanttotla"
  authorInstagram = "nishanttotla"
  coverImage = "http://nishanttotla.com/images/nishant.jpg"
  authorSignature = "nRT"